package GUI;
import javax.swing.JOptionPane;
import minesweeper.Minesweeper;

public class CustomMap extends javax.swing.JFrame {
    /**
     * Creates new form CustomMap
     */
    private final Minesweeper cMinesweeper;
    public CustomMap(Minesweeper iMinesweeper) {
        this.cMinesweeper = iMinesweeper;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        Grid_TextField = new javax.swing.JTextField();
        Button_Okay = new javax.swing.JButton();
        Mines_TextField = new javax.swing.JTextField();
        Custom_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(null);

        getContentPane().add(Grid_TextField);
        Grid_TextField.setBounds(180, 130, 55, 19);

        Button_Okay.setIcon(new javax.swing.ImageIcon("src/resources/img/Okay.jpg")); // NOI18N
        Button_Okay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Okay);
        Button_Okay.setBounds(100, 230, 96, 34);

        getContentPane().add(Mines_TextField);
        Mines_TextField.setBounds(180, 170, 55, 19);

        Custom_Background.setIcon(new javax.swing.ImageIcon("src/resources/img/Background/Final_Custom_BG.jpg")); // NOI18N
        getContentPane().add(Custom_Background);
        Custom_Background.setBounds(0, 0, 300, 300);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
//        dispose();
        try{
            Object eventSource = evt.getSource();
            String input = "0";
            input = Grid_TextField.getText();
            int size = Integer.parseInt(input);
            String input2 = "0";
            input2 = Mines_TextField.getText();
            int bomnum = Integer.parseInt(input2);
            if(size < 6 && bomnum == 0){
                JOptionPane.showMessageDialog(rootPane, "Cannot set size lower than 6 & bom is zero. Input Again");
            }
            else if(size < 6){
                JOptionPane.showMessageDialog(rootPane, "Cannot set size lower than 6. Input Again");
            }
            else if(bomnum == 0){
                JOptionPane.showMessageDialog(rootPane, "Cannot set bom zero. Input Again");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Sucessful");
                cMinesweeper.proceed(size,bomnum);
                dispose();

            }
        }
        catch(NumberFormatException var7){
            JOptionPane.showMessageDialog(rootPane, "Enter a valid integer!", "Invalid Input", 0);
        }


    }


    // Variables declaration - do not modify
    private javax.swing.JButton Button_Okay;
    private javax.swing.JLabel Custom_Background;
    private javax.swing.JTextField Grid_TextField;
    private javax.swing.JTextField Mines_TextField;
    // End of variables declaration
}
